### PR TITLE
Migrated all Match Icons to PNGs #465

### PR DESCRIPTION
**Pull request by azoitl**
As part of this migration the icons where polished, harmonized with Eclipse UI Guidelines and a 2x version is added.

https://github.com/eclipse/gef-classic/issues/465

### CODE REVIEW

**Comment by ptziegler** [comment]
Just a minor thing, but it feels like some of the larger icons are a little blurry.

For example, this is your icon:
matchsize@2x

Where I would expect something closer to this, where the arrows are a little bit more crisp.
matchsize@2x

**Comment by ptziegler** [comment]
Unrelated: Perhaps it also makes sense to look into converting those icons into SVGs, at some point. I believe that could save us a lot of work in the long run, when we want to create e.g. icons in 4x resolution.

**Comment by azoitl** [comment]
The blurriness on the arrows comes from how I tried to keep the original design. The arrows have blue and orange halos. I didn't understand where this came from. With your feedback I'll try to get rid of this and get them crisper. 

Not sure if SVG will help to much. Normally at the sizes of our icons manual adjustments will still be needed. At least from my experience sofar. But happy to experiment a bit later.

**Comment by ptziegler** [comment]
> The arrows have blue and orange halos. I didn't understand where this came from. With your feedback I'll try to get rid of this and get them crisper.

I've noticed that as well. But in my example I've reduced it to just a single pixel. Or generally, I get the impression that anti-aliasing doesn't really work well with such small icons.

> Not sure if SVG will help to much. Normally at the sizes of our icons manual adjustments will still be needed. At least from my experience sofar. But happy to experiment a bit later.

I'm currently cleaning up some WindowBuilder icons and so far, I had a very positive experience (positive as in the result, not the actual work of creating them... 😓). At least for geometric shapes, it think it's very helpful. But as I said: Completely unrelated.

**Comment by ptziegler** [comment]
@azoitl At the end of the day, I don't mind either way. If you think the icons are good, go for it.

**Comment by azoitl** [comment]
> @azoitl At the end of the day, I don't mind either way. If you think the icons are good, go for it.

Just polished them a bit more. I may give also SVGs a try. Always keen to improve my drawing skills.

**Comment by ptziegler** [comment]
Thank you going above and beyond for those icons! Do you want to contribute the SVGs as part of this or a separate pull request?

**Comment by azoitl** [comment]
> Thank you going above and beyond for those icons! Do you want to contribute the SVGs as part of this or a separate pull request?

Would try them for some new icons. So for a separate PR.

**Pull request merged**
