### PR TITLE
Remove com.ibm.icu package dependencies

### PR DESCRIPTION
**Pull request by Phillipus**
Remove com.ibm.icu package dependencies

See https://github.com/eclipse/gef-classic/issues/92

### CODE REVIEW

**Comment by vogella** [comment]
@azoitl can you review /test ? We did something similar in platform a while ago. com.ibm.icu is not actively maintained anymore, so it would be nice to get rid of it.

**Comment by Phillipus** [comment]
The following `com.ibm.icu.text.*` packages (and their `java.text.*` replacements) are used for message formatting and should be easy to test:

```
com.ibm.icu.text.DecimalFormat -> java.text.DecimalFormat
com.ibm.icu.text.NumberFormat -> java.text.NumberFormat 
com.ibm.icu.text.MessageFormat ->  java.text.MessageFormat 
```

But I'm not sure about:

```
com.ibm.icu.text.Bidi -> java.text.Bidi
com.ibm.icu.text.BreakIterator -> java.text.BreakIterator 
```

These are used in `BidiProcessor` and `FlowUtilities`. The `java.text.*` replacements seem to work OK from my simple tests, but that's not to say that there is something different in their handling for example in RTL text, or non-English languages.

**Comment by azoitl** [comment]
I had a look and run some of the samples. I could not notice anything. Furthermore there are some tests using the FlowUtilities. So here I think we are rather save. 

However there are no RTL test or non-English tests. 

But as pointed out by @Phillipus most of the changes are straight forward and bring a general improvement on the code. Therefore I'm in favor of merging the pull request.

**Comment by Phillipus** [comment]
If the PR is merged and end users report a problem with this version then the revert would be easy enough and we might  have a better idea why `com.ibm.icu.text.*` is used rather than `java.text.*`

**Comment by vogella** [comment]
Thanks @Phillipus and @azoitl

**Comment by Phillipus** [comment]
Thanks @vogella and @azoitl 

FWIW, we have a forked version of GEF and Draw2d for our app, Archi. I've made the same changes for that. As we get a few thousand downloads each month globally if there are any issues caused by this change, they'll soon show up.

**Comment by vogella** [comment]
@Phillipus maybe you can start contributing the changes of your fork to regular GEF?

**Comment by Phillipus** [comment]
> @Phillipus maybe you can start contributing the changes of your fork to regular GEF?

Yes, will do.

Waiting for a review of https://github.com/eclipse/gef-classic/pull/38

**Pull request merged**
