### PR TITLE
Update changelog and readme regarding Zest 2.0

### PR DESCRIPTION
**Pull request by ptziegler**

### CODE REVIEW

**Comment by azoitl** [comment]
Should we also put the short summary of the changes and what users need to do as you wrote in your very nice email to cross projects into the changelog?

**Comment by ptziegler** [comment]
I suppose that makes sense. Though it'll also have to wait until tomorrow, because this final sprint really left me drained 😅 .

**Comment by ptziegler** [comment]
I've added a few words regarding the deprecated LayoutAlgorithm interface and listed the relevant, deprecated features.

**Review by azoitl — APPROVED** [review]

**Comment by azoitl** [comment]
Thx I think this is a very nice overview.

**Pull request merged**
