### PR TITLE
Introduce getChildrenRevIterable for Figure

### PR DESCRIPTION
**Pull request by azoitl**
With that the points which are iterating in reverse over all children are clearer marked.

### CODE REVIEW

**Comment by azoitl** [comment]
@Destrolaric thx in advance for any feedback.

**Comment by Destrolaric** [comment]
@azoitl Hmm, is the second class needed? If we add interface to existing class this will probably be backwards compatible.

**Comment by azoitl** [comment]
> @azoitl Hmm, is the second class needed? If we add an interface to the existing class, this will probably be backward compatible.

unfortunately if I added the interface to the first one API analysis tool is not happy and I didn't want to add a new exception to it. Also I didn't like the name of the first class as it didn't convey the meeting. I now changed it to  give the second class a better name and deprecated the first one. 

Within Draw2d I'm no only using the iterable and foreach loops. I think this will minimize the impact.

**Comment by azoitl** [comment]
@Destrolaric sorry for poking you again. I should do today the 3.15 M1 build and would love to have this commit on board. Did you found time to look at my update?

**Comment by Destrolaric** [comment]
@azoitl I think it should be okay.

**Pull request merged**
