### PR TITLE
Upgraded Java requirements to Java 17

### PR DESCRIPTION
**Pull request by azoitl**

### CODE REVIEW

**Comment by azoitl** [comment]
@ptziegler as promised here the patch for Java 17

**Comment by azoitl** [comment]
Did some further tests with Eclipse 4diac and also with the GEF Examples. Noticed that I forgot to upgrade some versions. Also i fixed as part of these some API check issues.

**Comment by azoitl** [comment]
And I always forget to mention the Issues in my PR. So this PR fixes #146.

**Comment by azoitl** [comment]
I finally managed to get test results from all platforms. If nobody objects I would merge this now.

/cc @Phillipus @ptziegler @Destrolaric  @vogella

**Comment by vogella** [comment]
+1 Lets go Java 17!!!

**Comment by Phillipus** [comment]
Can we stay on Java 8?

Just kidding. :-)

+1 for Java 17!

**Comment by azoitl** [comment]
@Phillipus your comment made my day :-D

**Comment by Destrolaric** [comment]
@azoitl DBeaver recently updated to Java 17. No issues from our side for GEF to update to Java 17.

**Comment by azoitl** [comment]
Thanks for all the positive feedback. Will merge.

**Pull request merged**
