### PR TITLE
GH verification build on Linux and Windows and multiple Java versions

### PR DESCRIPTION
**Pull request by vogella**
Currently we use Java 11 and Java 17, if GEF moves to Java 17 we may want to use latest and greatest in addition to Java 17.

### CODE REVIEW

**Comment by azoitl** [comment]
@vogella VM is set-up with Eclipse, cloned gef classic, fetched your pull request (less then 15 mins) I must say Eclipse dev never was smoother. Congrats to the platform team. But how should I test your PR.

**Comment by azoitl** [comment]
@vogella I had a look at the build output. As this is the first doc project to be build and looking at the output, for me it looks like maven can not access the java doc executable or that the java doc variable is not set. But I'm really really bad with maven.

**Comment by Phillipus** [comment]
I'm investigating...

**Comment by Phillipus** [comment]
In the three files `buildDoc.xml` it needs this line:

`<available file="${java.home}/bin/javadoc.exe" property="javadoc" value="${java.home}/bin/javadoc.exe" />`

The following existing one is unlikely ever to be found:

`<available file="${java.home}/../bin/javadoc.exe" property="javadoc" value="${java.home}/../bin/javadoc.exe" />`

**Comment by Phillipus** [comment]
https://github.com/eclipse/gef-classic/pull/156

**Comment by Phillipus** [comment]
Tested the build on Mac as well as Windows. Mac needs https://github.com/eclipse/gef-classic/pull/157

**Comment by Phillipus** [comment]
> If you have time please add Mac to the matrix. 

https://github.com/eclipse/gef-classic/pull/158

**Pull request merged**
