### PR TITLE
Update maven.yml

### PR DESCRIPTION
**Pull request by azoitl**
upgraded to java 17 as tycho 3.0. needs Java 17

### CODE REVIEW

**Comment by azoitl** [comment]
@vogella @Phillipus do you see any issues building GEF with Java 17? I would love to have our build on the latest Eclipse Tycho.

**Comment by Phillipus** [comment]
Will it still run under 11 for end users?

**Comment by azoitl** [comment]
> Will it still run under 11 for end users?

Yes definitely. But I may have to change something in my other pull request.

**Comment by Phillipus** [comment]
@azoitl If Tycho is building with Java 17 and we have:

```
<maven.compiler.source>11</maven.compiler.source>
<maven.compiler.target>11</maven.compiler.target>	
```

Will it actually create 11 compliant byte code? Normally one would use a `toolchains.xml` file to specify a path to JDK 11 otherwise Tycho complains with:

`[WARNING] Using JavaSE-17 to fulfill requested profile of JavaSE-11 this might lead to faulty dependency resolution, consider define a suitable JDK in the toolchains.xml`

**Comment by azoitl** [comment]
I hope so. But I'm not a maven expert. Any suggestions are warmly welcome here.

**Comment by Phillipus** [comment]
> I hope so. But I'm not a maven expert. Any suggestions are warmly welcome here.

I think it should be OK from my tests with building Archi with these settings. But also not an expert. @vogella WDYT?

**Pull request merged**
