### PR TITLE
[Modernize Code] Turn Editpart children into typed List

### PR DESCRIPTION
**Pull request by azoitl**
One of the biggest drawbacks of current GEF Classic code is that it is not yet using typed generics. This requires a lot of checks and casts in client code. This commit is a start to move GEF Classic to a more modern java.

### CODE REVIEW

**Comment by vogella** [comment]
@[azoitl](https://github.com/azoitl) please rebase.

**Comment by vogella** [comment]
Thanks @azoitl

**Comment by pcdavid** [comment]
I think this change [broke GMF Runtime](https://ci.eclipse.org/gmf-runtime/job/gmf-runtime-canary/jdk=openjdk-jdk11-latest,label=migration/18/console) (again), and maybe other downstream projects (I suspect Sirius too, but have not confirmed yet):

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:05 min
[INFO] Finished at: 2022-07-09T20:52:39Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:2.7.2:compile (default-compile) on project org.eclipse.gmf.runtime.diagram.ui: Compilation failure: Compilation failure: 
[ERROR] /home/jenkins/agent/workspace/gmf-runtime-canary/jdk/openjdk-jdk11-latest/label/migration/bundles/org.eclipse.gmf.runtime.diagram.ui/src/org/eclipse/gmf/runtime/diagram/ui/editpolicies/ContainerEditPolicy.java:[286] 
[ERROR] 	editparts = ((IGraphicalEditPart)getHost()).getChildren();          
[ERROR] 	            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] Type mismatch: cannot convert from List<EditPart> to List<IGraphicalEditPart>
[ERROR] 1 problem (1 error)
```

**Comment by pcdavid** [comment]
I confirm that this breaks Sirius too:

```
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:2.7.1:compile (default-compile) on project org.eclipse.sirius.diagram.ui: Compilation failure: Compilation failure: 
[ERROR] /home/pcdavid/p/eclipse/git/org.eclipse.sirius/plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/internal/util/EditPartQuery.java:[165] 
[ERROR] 	Iterable<IBorderItemEditPart> bordersItemPart = Iterables.filter(part.getChildren(), Predicates.and(Predicates.instanceOf(IBorderItemEditPart.class), new Predicate<IBorderItemEditPart>() {
[ERROR] 	                                                          ^^^^^^
[ERROR] The method filter(Iterable<T>, Predicate<? super T>) in the type Iterables is not applicable for the arguments (List<EditPart>, Predicate<IBorderItemEditPart>)
[ERROR] /home/pcdavid/p/eclipse/git/org.eclipse.sirius/plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/internal/commands/SnapCommand.java:[126] 
[ERROR] 	List<IGraphicalEditPart> editParts = (List<IGraphicalEditPart>) newEditPart.getChildren().stream().filter(ep -> {
[ERROR]                 return !(ep instanceof IDiagramBorderNodeEditPart) && ep instanceof IGraphicalEditPart;
[ERROR]             }).collect(Collectors.toList());
[ERROR] 	                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] Cannot cast from List<EditPart> to List<IGraphicalEditPart>
[ERROR] /home/pcdavid/p/eclipse/git/org.eclipse.sirius/plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/graphical/edit/policies/SiriusContainerEditPolicy.java:[129] 
[ERROR] 	editparts = ((IGraphicalEditPart) getHost()).getChildren();
[ERROR] 	            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] Type mismatch: cannot convert from List<EditPart> to List<IGraphicalEditPart>
[ERROR] /home/pcdavid/p/eclipse/git/org.eclipse.sirius/plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/internal/layout/provider/BorderItemAwareLayoutProvider.java:[1581] 
[ERROR] 	final Collection<IGraphicalEditPart> children = Collections2.filter(part.getChildren(), Predicates.and(Predicates.instanceOf(IGraphicalEditPart.class),
[ERROR]                 Predicates.not(Predicates.instanceOf(AbstractDiagramBorderNodeEditPart.class)), Predicates.not(Predicates.instanceOf(AbstractDiagramNameEditPart.class))));
[ERROR] 	                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] Type mismatch: cannot convert from Collection<EditPart> to Collection<IGraphicalEditPart>
[ERROR] /home/pcdavid/p/eclipse/git/org.eclipse.sirius/plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/internal/layout/provider/BorderItemAwareLayoutProvider.java:[1586] 
[ERROR] 	final Collection<IGraphicalEditPart> grandchildren = Collections2.filter(child.getChildren(), Predicates.and(Predicates.instanceOf(IGraphicalEditPart.class),
[ERROR]                         Predicates.not(Predicates.instanceOf(AbstractDiagramBorderNodeEditPart.class)), Predicates.not(Predicates.instanceOf(AbstractDiagramNameEditPart.class))));
[ERROR] 	                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] Type mismatch: cannot convert from Collection<EditPart> to Collection<IGraphicalEditPart>
[ERROR] /home/pcdavid/p/eclipse/git/org.eclipse.sirius/plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/internal/layout/provider/BorderItemAwareLayoutProvider.java:[1620] 
[ERROR] 	final Collection<IGraphicalEditPart> children = Collections2.filter(part.getChildren(), Predicates.and(Predicates.instanceOf(IGraphicalEditPart.class),
[ERROR]                 Predicates.not(Predicates.instanceOf(AbstractDiagramBorderNodeEditPart.class)), Predicates.not(Predicates.instanceOf(AbstractDiagramNameEditPart.class))));
[ERROR] 	                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] Type mismatch: cannot convert from Collection<EditPart> to Collection<IGraphicalEditPart>
[ERROR] /home/pcdavid/p/eclipse/git/org.eclipse.sirius/plugins/org.eclipse.sirius.diagram.ui/src-diag/org/eclipse/sirius/diagram/ui/tools/internal/layout/provider/BorderItemAwareLayoutProvider.java:[1625] 
[ERROR] 	final Collection<IGraphicalEditPart> grandchildren = Collections2.filter(child.getChildren(), Predicates.and(Predicates.instanceOf(IGraphicalEditPart.class),
[ERROR]                         Predicates.not(Predicates.instanceOf(AbstractDiagramBorderNodeEditPart.class)), Predicates.not(Predicates.instanceOf(AbstractDiagramNameEditPart.class))));
[ERROR] 	                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] Type mismatch: cannot convert from Collection<EditPart> to Collection<IGraphicalEditPart>
[ERROR] 7 problems (7 errors)
```

**Comment by azoitl** [comment]
@pcdavid thanks for letting me know. I really hoped that you don't have that kind of casts. But I totally understand why you have them. In my pull request https://github.com/eclipse/gef-classic/pull/89 I have for sure fixed the GMF problem I'm not so sure about the Sirius problem.  Is there some easy way that I can experiment up front with my changes? Would you accept pullrequests for GMF and Sirius, espeically when it would just be adding casts?

**Comment by vogella** [comment]
@azoitl I think PR are always welcome, I would recommend start sending some.

**Comment by vogella** [comment]
@azoitl @pcdavid what is the status here?

**Comment by azoitl** [comment]
Unfortunately I haven't heard anything from @pcdavid.

**Comment by pcdavid** [comment]
I completely understand the appeal of wanting a more "modern" code base, but this is exactly the kind of disrupting change "for the sake of change" that I warned about in [my mail to gef-dev](https://www.eclipse.org/lists/gef-dev/msg02145.html).

This broke GMF and Sirius for sure, and possibly many other projects which have been working perfectly fine for years. Graphiti? Capella? Ecore Tools? Papyrus? UML Designer? Maybe, maybe not, but who knows, and who will take the time to check, contact the projects if they are impacted, propose patches, release the new versions, etc.?
And this is just the few Eclipse/Open Source projects I can think of in 30s. How many other projects in the greater ecosystem may discover in a few months that they are no longer compatible with the new SimRel if this change (or others like it) go into it?

All for zero functional benefit.

Please reconsider this change.

**Comment by vogella** [comment]
@[azoitl](https://github.com/azoitl) I suggest to revert this for now and see if we can find a backward compatible solution. Can you please provide a PR for the revert?

**Comment by vogella** [comment]
Thanks @pcdavid for the feedback.

**Comment by azoitl** [comment]
@pcdavid first of all I'm very sorry that I broke clients. This was definitely not my intent. I am aware of the special situation of GEF and I'm strongly evaluating my proposed changes. It seems I have to still learn a lot. I started with things that disturbed me most as GEF user in the last 12 years I'm developing an application based on GEF Classic. 

One of the reasons I think GEF Classic code should be modernized is to keep it maintainable. Dependencies of GEF Classic get obsolete (e.g., #93), Eclipse platform is changing and if we are not keeping up GEF Classic as a whole will be obsolete and all clients with it. 

But as @pcdavid pointed out we have to be more carefull. @pcdavid would you be so kind and have a web-meeting with me. I would like to know more about your requirements and also learn how I could detect such problems already on my develop machine. 

If anyone else reads and has tips for me feel free to contact me. 

@vogella sure I will provide a revert commit later today.

**Comment by azoitl** [comment]
Revert commit is in pullrequest #94.

**Comment by vogella** [comment]
@azoitl one way to modernize the GEF code base would be to keep critical methods as they are, deprecate them and offer new methods based on the generic type information. Can you open a ticket for this work so that we can try to archive this without breaking GMF? 

@pcdavid revert https://github.com/eclipse/gef-classic/pull/94 has been commited. Does that fix GMF / Sirius?

**Comment by pcdavid** [comment]
Thanks. I can't have a look right now. Maybe tomorrow or this week-end.

**Comment by azoitl** [comment]
> @azoitl one way to modernize the GEF code base would be to keep critical methods as they are, deprecate them and offer new methods based on the generic type information. Can you open a ticket for this work so that we can try to archive this without breaking GMF?

I thought about this too. But GEF Classic allready has a lot of deprecated API. I hoped I find ways to not add more. I have to sleep this a bit over. The goal of my modernization attempts was mostly to improve GEF Classic API for its users. But in retrospect I need to setup some kind of sendbox for my experiments. I'm thinking of something like setting up GMF, Graphiti, Sirus, 4diac, Archimate builds  to test my experiments and have a representative set of GEF Classic users. 

Also I'm thinking cleaning up internal non api code. Which has less advantages for the users but helps us to easier maintain GEF classic. 

But as said I will not to think a bit about the next steps.

In the mean-time I think it is more important that we get GEF classic's dependencies cleaned for the 2022-09 release train.

**Pull request merged**
