### PR TITLE
Reintegrate Zest 2.x fork into master

### PR DESCRIPTION
**Pull request by ptziegler**

### CODE REVIEW

**Comment by ptziegler** [comment]
@azoitl I've rebased the branch for a final time and from my perspective, we're good to go. Is there anything still open or can I finally press this big green button?

**Comment by ptziegler** [comment]
How can there be "conflicts", dear GitHub?...

image

**Comment by ptziegler** [comment]
I have no clue what GitHub was on about, but I suppose the merge has worked now...

**Comment by azoitl** [comment]
> I have no clue what GitHub was on about, but I suppose the merge has worked now...

We don't have to understand everything ;-)

**Pull request merged**
