### PR TITLE
Final Clean-up of shapes example. Mostly externalize strings

### PR DESCRIPTION
**Pull request by azoitl**

### CODE REVIEW

**Comment by ptziegler** [comment]
Out of curiosity, is there any reason you prefer `MessageFormat.format(...)` over `Messages.bind(...)`?

**Comment by azoitl** [comment]
> Out of curiosity, is there any reason you prefer `MessageFormat.format(...)` over `Messages.bind(...)`?

I guess the main reason is that I learned about i18n with using `MessageFormat.format(...)`. I personally don't have any preferences. Is `Messages.bind(...)` better?

**Comment by ptziegler** [comment]
> > Out of curiosity, is there any reason you prefer `MessageFormat.format(...)` over `Messages.bind(...)`?
> 
> I guess the main reason is that I learned about i18n with using `MessageFormat.format(...)`. I personally don't have any preferences. Is `Messages.bind(...)` better?

They effectively do the same. The upside: `Messages.bind(...)` doesn't require an additional import. The downside: `Messages.bind(...)` doesn't support varargs. So if you have more than two parameters, you have to wrap them inside a `new Object[]{...}`.

**Comment by azoitl** [comment]
> > > Out of curiosity, is there any reason you prefer `MessageFormat.format(...)` over `Messages.bind(...)`?
> > 
> > 
> > I guess the main reason is that I learned about i18n with using `MessageFormat.format(...)`. I personally don't have any preferences. Is `Messages.bind(...)` better?
> 
> They effectively do the same. The upside: `Messages.bind(...)` doesn't require an additional import. The downside: `Messages.bind(...)` doesn't support varargs. So if you have more than two parameters, you have to wrap them inside a `new Object[]{...}`.

Do you have any preferences? Personally I would be happy to try out `Messages.bind`

**Comment by merks** [comment]
There's also org.eclipse.osgi.util.NLS.bind.  😱

**Comment by azoitl** [comment]
More options, yeah! What is the Eclipse preferred way?

**Comment by merks** [comment]
In the order of search matches:

image

image

image

I have no opinion.  😁

**Pull request merged**
