### PR TITLE
Stabilized Draw2d Tests

### PR DESCRIPTION
**Pull request by azoitl**
ConnectionEndPointMove test did correctly wait for all updates to be dispatched. This resulted in different test results depending if executed alone or as part of Draw2d's test suite. This is fixed now.

### CODE REVIEW

**Comment by azoitl** [comment]
After some poking around I think I got the not so stable Draw2d tests into a stage that they are giving us reasonable feedback. or that I had to deactivate some tests: only flowpages and their breaking up  of text. 

What do you think @Phillipus @Destrolaric.

@ptziegler with this PR we would be ready for your improvements of Draw2d.

**Comment by Phillipus** [comment]
> What do you think @Phillipus @Destrolaric.

I think you did a good job to stabilize this. :-)

Moving forward we need a stable test suite that passes so we can test against new commits. I think we're at that point now.

**Comment by azoitl** [comment]
> > What do you think @Phillipus @Destrolaric.
> 
> I think you did a good job to stabilize this. :-)
> 
> Moving forward we need a stable test suite that passes so we can test against new commits. I think we're at that point now.

Thx. I only fear that I fixed some symptoms. @Phillipus do you have any idea how we can get the macos build not canceled? Or is this because some quotas?

**Comment by Phillipus** [comment]
> do you have any idea how we can get the macos build not canceled? Or is this because some quotas?

It could be because of the quota. You can test this by running the tests on your fork.

**Comment by azoitl** [comment]
> > do you have any idea how we can get the macos build not canceled? Or is this because some quotas?
> 
> It could be because of the quota. You can test this by running the tests on your fork.

Ah didn't think about that. Yes in my fork macos builds.

**Pull request merged**
