### PR TITLE
Add missing parenthesis using the Eclipse clean-up feature

### PR DESCRIPTION
**Pull request by azoitl**
@ptziegler as suggested a full clean-up of all missing parenthesis. I hope this greatly reduces the noise for future fixes.

### CODE REVIEW

**Comment by ptziegler** [comment]
I skimmed over it and everything seems to be good. I find it a little weird how the clean-up feature also cleaned-up the imports and changed for-loops into for-each loops, but I suppose that's fine.

**Comment by azoitl** [comment]
> I skimmed over it and everything seems to be good. I find it a little weird how the clean-up feature also cleaned-up the imports and changed for-loops into for-each loops, but I suppose that's fine.

Ok that is interesting I created a configuration that should only clean the parenthesis. But cleaned for loops and imports is definitely nothing bad.

**Comment by ptziegler** [comment]
> Ok that is interesting I created a configuration that should only clean the parenthesis. But cleaned for loops and imports is definitely nothing bad.

The only problem is that for the raw lists, we now iterate over Objects. At some point it probably makes sense to search for all explicit casts and see where those can be removed.

**Comment by azoitl** [comment]
> The only problem is that for the raw lists, we now iterate over Objects. At some point it probably makes sense to search for all explicit casts and see where those can be removed.

Yes that is a point. I normally try to search for users of methods that I turn to generic. But it can easily be missed. Maybe there is a compiler warning we could turn on for that later.

**Pull request merged**
