### PR TITLE
Create integration tests using GEF examples and SWTBot.

### PR DESCRIPTION
**Pull request by ptziegler**
I dabbled a little into SWTBot and in general, this should all work out.

To note:
- The tests must not be executed in the UI thread.
- The record feature of SWTBot produces invalid Java code.

I'm not very creative when it comes to use cases, so right now I'm only testing basic features like add/removing items and/or connections. Or the Undo/Redo functionality.

### CODE REVIEW

**Comment by ptziegler** [comment]
The test failure in testWithRulers() is expected, due to a ConcurrentModificationException being thrown internally. The failure in testWithSnapToGrid() seems sporadic, as it only happens in a single run. I have to further investigate...

**Comment by ptziegler** [comment]
I've adjusted the validation to ignore all unrelated exceptions, meaning exceptions not thrown by GEF and/or Draw2D. Meaning something like this:

```
2024-06-24T21:27:40.6469740Z java.lang.IllegalArgumentException: java.nio.file.NoSuchFileException: file:/Users/runner/work/gef-classic/gef-classic/org.eclipse.gef.tests/target/work/Contents/Info.plist
2024-06-24T21:27:40.6471010Z 	at org.eclipse.urischeme.internal.registration.PlistFileWriter.getDom(PlistFileWriter.java:224)
2024-06-24T21:27:40.6471810Z 	at org.eclipse.urischeme.internal.registration.PlistFileWriter.<init>(PlistFileWriter.java:69)
2024-06-24T21:27:40.6472890Z 	at org.eclipse.urischeme.internal.registration.RegistrationMacOsX.getPlistFileWriter(RegistrationMacOsX.java:120)
2024-06-24T21:27:40.6473850Z 	at org.eclipse.urischeme.internal.registration.RegistrationMacOsX.changePlistFile(RegistrationMacOsX.java:136)
2024-06-24T21:27:40.6474740Z 	at org.eclipse.urischeme.internal.registration.RegistrationMacOsX.handleSchemes(RegistrationMacOsX.java:53)
2024-06-24T21:27:40.6475610Z 	at org.eclipse.urischeme.AutoRegisterSchemeHandlersJob.run(AutoRegisterSchemeHandlersJob.java:92)
2024-06-24T21:27:40.6476220Z 	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
2024-06-24T21:27:40.6477100Z Caused by: java.nio.file.NoSuchFileException: file:/Users/runner/work/gef-classic/gef-classic/org.eclipse.gef.tests/target/work/Contents/Info.plist
2024-06-24T21:27:40.6489890Z 	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
2024-06-24T21:27:40.6490520Z 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
2024-06-24T21:27:40.6491140Z 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
2024-06-24T21:27:40.6491800Z 	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:261)
2024-06-24T21:27:40.6492390Z 	at java.base/java.nio.file.Files.newByteChannel(Files.java:379)
2024-06-24T21:27:40.6492840Z 	at java.base/java.nio.file.Files.newByteChannel(Files.java:431)
2024-06-24T21:27:40.6493430Z 	at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420)
2024-06-24T21:27:40.6494010Z 	at java.base/java.nio.file.Files.newInputStream(Files.java:159)
2024-06-24T21:27:40.6494460Z 	at java.base/java.nio.file.Files.newBufferedReader(Files.java:2897)
2024-06-24T21:27:40.6494930Z 	at java.base/java.nio.file.Files.newBufferedReader(Files.java:2930)
2024-06-24T21:27:40.6495510Z 	at org.eclipse.urischeme.internal.registration.FileProvider.newReader(FileProvider.java:45)
2024-06-24T21:27:40.6496260Z 	at org.eclipse.urischeme.internal.registration.RegistrationMacOsX.lambda$7(RegistrationMacOsX.java:120)
2024-06-24T21:27:40.6497010Z 	at org.eclipse.urischeme.internal.registration.PlistFileWriter.getDom(PlistFileWriter.java:218)
2024-06-24T21:27:40.6497470Z 	... 6 more
```

**Comment by ptziegler** [comment]
@azoitl 

As mentioned, these 15-or-so test cases should cover some of the basic functionality of GEF. Feel free to tell me if you have any other use cases. ;D
Otherwise those should at least serve as a foundation and can always be extended, as users report bugs.

In total, this should increase the coverage from ~5% to 43%. Which isn't great but at least a start.
image

**Comment by ptziegler** [comment]
Unless there are any objections, I'll plan on merging this tomorrow. I don't expect any complications, as those are only tests.

**Comment by azoitl** [comment]
@ptziegler sorry somehow it was rather stressy on my side and this PR totally slipped through. I definitely would merge it as it is an great improvement towards more tests and more early feedback.

**Pull request merged**
