### PR TITLE
Convert Help sources from HTML to AsciiDoctor

### PR DESCRIPTION
**Pull request by ptziegler**
I'd like to merge this before #348, @azoitl. Meaning it won't happen before the M1, but I think that's fine.

Before:

image

After:

image

The conversion was done via https://alldocs.app/convert-html-to-asciidoc. It's not 100% perfect and some parts I have to adjust manually. But I haven't encountered any major obstacles.

### CODE REVIEW

**Comment by azoitl** [comment]
Cool! Thx for spending that effort.

**Comment by ptziegler** [comment]
I think it's easier if you check out the branch and look at the help directly, rather than the sources... Do note that I didn't manage to reproduce the "disabled" table columns.  There's probably a way to do this with some wacky CSS, but I'm not sure if this is really worth the effort...

image

image

**Comment by azoitl** [comment]
Looks good to me. Also I think the table issue is not that big. The only thing that I think should be changed is the headline of the commit message. Because the current one is a bit misleading.

**Comment by ptziegler** [comment]
> The only thing that I think should be changed is the headline of the commit message. Because the current one is a bit misleading.

Good point... I totally forgot to update it after also including GEF and Zest.

**Comment by azoitl** [comment]
@ptziegler When I now build on my local machine with the default eclipse builder I get the below attached exceptions for all three isv projects. Any idea what I need to configure or install?


```
Failed to execute mojo org.apache.maven.plugins:maven-antrun-plugin:1.6:run {execution: generate-sources} (org.apache.maven.plugins:maven-antrun-plugin:1.6:run:generate-sources:generate-sources)

org.eclipse.core.runtime.CoreException: Failed to execute mojo org.apache.maven.plugins:maven-antrun-plugin:1.6:run {execution: generate-sources}
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeMojo(MavenExecutionContext.java:340)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.lambda$0(MavenExecutionContext.java:291)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:394)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:275)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:290)
	at org.eclipse.m2e.core.project.configurator.MojoExecutionBuildParticipant.build(MojoExecutionBuildParticipant.java:57)
	at org.eclipse.m2e.core.internal.builder.MavenBuilderImpl.lambda$2(MavenBuilderImpl.java:153)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
	at org.eclipse.m2e.core.internal.builder.MavenBuilderImpl.build(MavenBuilderImpl.java:133)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:164)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:1)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.lambda$1(MavenBuilder.java:109)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:394)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:228)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.lambda$0(MavenBuilder.java:100)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:394)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:275)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:214)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.execute(MavenBuilder.java:83)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder.build(MavenBuilder.java:192)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:1079)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:296)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:352)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:441)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:444)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:555)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:503)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:585)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:207)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:300)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.apache.maven.plugin.MojoExecutionException: An Ant BuildException has occured: The following error occurred while executing this line:
/home/az/git/gef-classic/org.eclipse.gef.doc.isv/buildDoc.xml:6: The following error occurred while executing this line:
/home/az/git/gef-classic/org.eclipse.gef.doc.isv/buildDoc.xml:39: /home/az/git/gef-classic/org.eclipse.gef.doc.isv/api-context-libs does not exist.
	at org.apache.maven.plugin.antrun.AntRunMojo.execute(AntRunMojo.java:283)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:126)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeMojo(MavenExecutionContext.java:338)
	... 32 more
Caused by: /home/az/git/gef-classic/org.eclipse.gef.doc.isv/target/antrun/build-main.xml:4: The following error occurred while executing this line:
/home/az/git/gef-classic/org.eclipse.gef.doc.isv/buildDoc.xml:6: The following error occurred while executing this line:
/home/az/git/gef-classic/org.eclipse.gef.doc.isv/buildDoc.xml:39: /home/az/git/gef-classic/org.eclipse.gef.doc.isv/api-context-libs does not exist.
	at org.apache.tools.ant.ProjectHelper.addLocationToBuildException(ProjectHelper.java:497)
	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:444)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
	at jdk.internal.reflect.GeneratedMethodAccessor70.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:390)
	at org.apache.tools.ant.Target.performTasks(Target.java:411)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1397)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1366)
	at org.apache.maven.plugin.antrun.AntRunMojo.execute(AntRunMojo.java:270)
	... 34 more
Caused by: /home/az/git/gef-classic/org.eclipse.gef.doc.isv/buildDoc.xml:6: The following error occurred while executing this line:
/home/az/git/gef-classic/org.eclipse.gef.doc.isv/buildDoc.xml:39: /home/az/git/gef-classic/org.eclipse.gef.doc.isv/api-context-libs does not exist.
	at org.apache.tools.ant.ProjectHelper.addLocationToBuildException(ProjectHelper.java:497)
	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:444)
	at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:105)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
	at jdk.internal.reflect.GeneratedMethodAccessor70.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:390)
	at org.apache.tools.ant.Target.performTasks(Target.java:411)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1397)
	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1249)
	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:442)
	... 45 more
Caused by: /home/az/git/gef-classic/org.eclipse.gef.doc.isv/buildDoc.xml:39: /home/az/git/gef-classic/org.eclipse.gef.doc.isv/api-context-libs does not exist.
	at org.apache.tools.ant.types.AbstractFileSet.getDirectoryScanner(AbstractFileSet.java:474)
	at org.apache.tools.ant.types.FileSet.iterator(FileSet.java:69)
	at org.apache.tools.ant.types.resources.Union.getCollection(Union.java:123)
	at org.apache.tools.ant.types.resources.Union.getCollection(Union.java:107)
	at org.apache.tools.ant.types.resources.BaseResourceCollectionContainer.cacheCollection(BaseResourceCollectionContainer.java:265)
	at org.apache.tools.ant.types.resources.BaseResourceCollectionContainer.iterator(BaseResourceCollectionContainer.java:142)
	at org.apache.tools.ant.types.Path.iterator(Path.java:704)
	at org.apache.tools.ant.types.Path.iterator(Path.java:698)
	at org.apache.tools.ant.types.resources.Resources$MyCollection$MyIterator.hasNext(Resources.java:97)
	at org.apache.tools.ant.util.CollectionUtils.asCollection(CollectionUtils.java:218)
	at org.apache.tools.ant.types.resources.Resources$MyCollection.getCache(Resources.java:83)
	at org.apache.tools.ant.types.resources.Resources$MyCollection.iterator(Resources.java:78)
	at org.apache.tools.ant.types.resources.Resources.iterator(Resources.java:170)
	at org.apache.tools.ant.types.resources.Union.getCollection(Union.java:123)
	at org.apache.tools.ant.types.resources.Union.getCollection(Union.java:107)
	at org.apache.tools.ant.types.resources.BaseResourceCollectionContainer.cacheCollection(BaseResourceCollectionContainer.java:265)
	at org.apache.tools.ant.types.resources.BaseResourceCollectionContainer.iterator(BaseResourceCollectionContainer.java:142)
	at org.apache.tools.ant.taskdefs.PathConvert.execute(PathConvert.java:364)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
	at jdk.internal.reflect.GeneratedMethodAccessor70.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:390)
	at org.apache.tools.ant.Target.performTasks(Target.java:411)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1397)
	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1249)
	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:442)
	... 58 more
```

**Comment by ptziegler** [comment]
Hm... that's weird. I'll have a look later today.

**Comment by ptziegler** [comment]
The goals of the `maven-dependency-plugin` aren't executed _for some reason_...
As a result the `api-context-libs` and `linkoffline-target` folders are never created, which then causes the ant task to crash.

In order to get the workspace functional again, I'll disable the the ant task while inside the IDE, later today. In the meantime you can get around this problem by running a `mvn clean verify` on the command line.

This way you'd still get the html files but not the JavaDoc, meaning those links would still appear broken (Which is how it used to be up until now, btw.)

**Pull request merged**
